name: Deploy Rust Site
on:
  push:
    branches: [main] # или master, смотря какая у тебя главная

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install Trunk
        run: wget -qO- https://github.com/trunk-rs/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - name: Build with Trunk
        run: ./trunk build --release --public-url /${{ github.event.repository.name }}/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Trunk кладет готовый сайт сюда
          branch: gh-pages # Робот сам создаст эту ветку
